### ISSUE TITLE
[FEAT] 멋사 1차 과제🦁

### ISSUE THREAD

**Issue by nayujin-dev** [Likelion-at-SMWU-10th/NaYuJin#3]
## 📌  Feature Issue
git flow 협업 플로우 익히기

## 📝  To-do

- [ ] issue 생성
- [ ] main 브랜치에서 과제 브랜치 생성
- [ ] 해당 브랜치에서 파일 생성
- [ ] add, commit, push
- [ ] PR작성(태그하기)
